### ISSUE TITLE
Add rules option

### ISSUE THREAD

**Issue by mrtryhard** [mrtryhard/simplepass#1]
## Reviewing
- [x] Empty rule should not crash 
- [x] Invalid rule should not crash
- [x] Bad combinations of options (-s, -r & -l) should return help page. (MOVE TO #2 Refactor Main issue). 
- [x] Rules shouldn't execute verification
- [x] Must run on Windows and Linux 
## Post-review
- [x] Rule `simplepass -r "\\"` shouldn't hang program. Expected output is `\`.
- [x] The unescaped dot `.` as in `-r ".[abc]"` should generate a random character, not a dot.
## TODO
- [x] RangeRule 
- [x] SlashRule
- [x] QuantityRule 
- [x] RuleExecutor 
  - [x] RangeRule `[ ]` parsing.
  - [x] QuantityRule `{ }` parsing.
  - [x] SlashRule parsing `\x`.
  - [x] Parsed and interpreted output. 
  - [x] Exclusion operator `^` inside range `[ ]`.
  - [x] Exclusion operator `^` outside range `[ ]`.
  - [x] :no_good: Zero-to-many quantifier `*` (Does this make sense in a generation context? -no)
  - [x] :no_good: One-to-many quantifier `+` (Does this make sense in a generation context? -no)
  - [x] Escape operator `\` outside rules.
- [x] Documentation on new features
  - [x] Wiki page.
  - [x] Update -h command line argument.
## Description

Sample use cases:  
`simplepass -r "[0-9]{5}\\W{30}"`  
Would output a 35 characters long password starting with five digits. 

The rules filter would use the regex model, without capture groups.

The `-r` option won't be allowed `-s` as they would cause conflicts.  
In case of `-l` specified, it will specify the max length to be used to generate the password, regardless of the last specified length rule within `-r`.
## Draft Documentation

```
RangeRule: [], [x-y]
  RangeRule(string rule, bool exclude = false)
    [abc] -> rule=abc, exclude=false
    [^abc] -> rule=abc, exclude=true
    [a-cz] -> rule=a-cz, exclude=false // only a up to c (abc) or z. 
    [a-cz] -> rule=a-cz, exclude=true // only char not a,b,c and z
    // Cannot put QuantityRule in [] (only following). 
    // Cannot put \x in it. 

QuantityRule: {}, *, + 
  QuantityRule(int min, int max). {x} -> min == max = x 
                                  {a,b} -> min = min(a,b), max = max(a,b)  
                                  * -> min = 0, max = MAX_LENGTH
                                  + -> min = 1, max = MAX_LENGTH
  // Only numerics in {}
SlashTypeRule: \x and . where x can be s, S, W, w, ., d, D
  // Special case. 
  \s -> directly a space 
  \S -> no space... not quite useful. 
  \w -> [a-zA-Z]
  \W -> [^a-zA-Z] -> [0-9]
  \. -> directly a dot 
  \d -> [0-9]
  \D -> [^0-9]
```
## Criterias
- Empty rule should return a controlled error. 
- Invalid rule should not crash.
- A bad combination of commands should return help.
- Rules should not verify their inputs. RuleExecutor should. 
- Must run on both Linux and Windows without any usability differences.

**Comment by mrtryhard** [comment]
Updated. Added small draft.

**Comment by mrtryhard** [comment]
Slash not yet support by RuleExecutor.  
^ exclusion not supported outside [](RangeRule).   
- and + quantifiers are not yet supported.  
  \ escaper not yet supported.

**Comment by mrtryhard** [comment]
Moved point "Refactor main" as its own issue.

**Comment by mrtryhard** [comment]
Ready to merge to master with 1.1 milestone.
