### ISSUE TITLE
Refactor main

### ISSUE THREAD

**Issue by mrtryhard** [mrtryhard/simplepass#2]
Refactor main so it becomes readable and easy to add commands. 
## TODO
- [x] Improve readability 
## Review criterias
- [x] **Having `-r` and any other options should trigger the help page or a specific message.** _to fix_
- [x] Old arguments `-s`, `-l`, `-h` should work as before.
- [x] **Must work flawlessly on Linux and Windows.**  _Bash bug where output is on the same line as the breadcrumb._.

**Comment by mrtryhard** [comment]
See getopt

Nevermind, isn't a portable solution. 

Creating a RuleBuilder will be better

**Comment by mrtryhard** [comment]
Removed direct dependencies on C libraries, making compilation a bit more soft. 
Code now cleared.
